---

- name: add key for Docker repository
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

#Ofc can be done as above, but well, I wanted to show I know 'with items' as well 
- name: add Docker repository
  apt_repository: repo="{{ item }}" state=present
  with_items:
    - "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ vagrant_image }} stable"

- name: Install Docker CE
  apt: pkg=docker-ce update_cache=yes 

- name: Download Docker Machine
  get_url:
    url: https://github.com/docker/machine/releases/download/v{{ docker_machine_version }}/docker-machine-{{ os }}-{{ architecture }} 
    dest: /usr/local/bin/docker-machine
    mode: 0755

- name: Download Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ os }}-{{ architecture }} 
    dest: /usr/local/bin/docker-compose
    mode: 0755

# To make testing easier
- name: Add user vagrant to docker group
  user:
    name: '{{ vagrant_user }}'
    groups: docker
    append: yes