FROM {{ jenkins_image }}

RUN /usr/local/bin/install-plugins.sh configuration-as-code configuration-as-code-support workflow-aggregator timestamper ws-cleanup credentials git ssh-slaves matrix-auth job-dsl